<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="guiaApe5" nsURI="http://www.example.org/guiaApe5" nsPrefix="guiaApe5">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Contenedor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="tienePrimaryKeySiNoVisual noMismoNombre noAsocioConmigo soloUnPrimaryKey tipoDeDatoObligatorioSiNoVisual visualNoRelacionaNiTieneClave"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="tienePrimaryKeySiNoVisual" value="not self.esVisual implies self.posee -> exists(e|e.isPrimary)"/>
      <details key="noMismoNombre" value="self.posee -> isUnique(e|e.name)"/>
      <details key="noAsocioConmigo" value="not self.relaciona -> includes(self)"/>
      <details key="soloUnPrimaryKey" value="self.posee -> select(e| e.isPrimary)-> size()&lt;=1"/>
      <details key="tipoDeDatoObligatorioSiNoVisual" value="not self.esVisual implies self.posee ->forAll(e| not e.tipoDato.oclIsUndefined())"/>
      <details key="visualNoRelacionaNiTieneClave" value="self.esVisual implies (self.posee->forAll(e|not e.isPrimary) and self.relaciona->isEmpty())"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="posee" lowerBound="1" upperBound="-1"
        eType="#//Elemento" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relaciona" upperBound="-1"
        eType="#//Contenedor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="main" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esVisual" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sistema">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="nombreUnicoPorContenedor"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="nombreUnicoPorContenedor" value="self.contiene->isUnique(c|c.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contiene" upperBound="-1"
        eType="#//Contenedor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Elemento">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="longitudCadena"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="longitudCadena" value="self.tipoDato = TipoDato :: String implies self.longitud>0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimary" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="longitud" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tipoDato" eType="#//TipoDato"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="esObligatorio" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TipoDato">
    <eLiterals name="String"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="boolean" value="2"/>
    <eLiterals name="double" value="3"/>
  </eClassifiers>
</ecore:EPackage>
