/*
 * generated by Xtext 2.38.0
 */
package guiaApe5.parser.antlr;

import com.google.inject.Inject;
import guiaApe5.parser.antlr.internal.InternalGuiaApe5Parser;
import guiaApe5.services.GuiaApe5GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class GuiaApe5Parser extends AbstractAntlrParser {

	@Inject
	private GuiaApe5GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalGuiaApe5Parser createParser(XtextTokenStream stream) {
		return new InternalGuiaApe5Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Sistema";
	}

	public GuiaApe5GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(GuiaApe5GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
