/*
 * generated by Xtext 2.38.0
 */
package guiaApe5.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class GuiaApe5ScopeProvider extends AbstractGuiaApe5ScopeProvider {

}
