/*
 * generated by Xtext 2.38.0
 */
package guiaApe5.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class GuiaApe5GrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class SistemaElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.Sistema");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSistemaKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cContieneKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cContieneAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cContieneContenedorParserRuleCall_6_0 = (RuleCall)cContieneAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cCommaKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cContieneAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cContieneContenedorParserRuleCall_7_1_0 = (RuleCall)cContieneAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Sistema returns Sistema:
		//    'Sistema'
		//    name=EString
		//    '{'
		//        'contiene' '=' '{' contiene+=Contenedor (',' contiene+=Contenedor)* '}'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Sistema'
		//name=EString
		//'{'
		//    'contiene' '=' '{' contiene+=Contenedor (',' contiene+=Contenedor)* '}'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Sistema'
		public Keyword getSistemaKeyword_0() { return cSistemaKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'contiene'
		public Keyword getContieneKeyword_3() { return cContieneKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//contiene+=Contenedor
		public Assignment getContieneAssignment_6() { return cContieneAssignment_6; }
		
		//Contenedor
		public RuleCall getContieneContenedorParserRuleCall_6_0() { return cContieneContenedorParserRuleCall_6_0; }
		
		//(',' contiene+=Contenedor)*
		public Group getGroup_7() { return cGroup_7; }
		
		//','
		public Keyword getCommaKeyword_7_0() { return cCommaKeyword_7_0; }
		
		//contiene+=Contenedor
		public Assignment getContieneAssignment_7_1() { return cContieneAssignment_7_1; }
		
		//Contenedor
		public RuleCall getContieneContenedorParserRuleCall_7_1_0() { return cContieneContenedorParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class ContenedorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.Contenedor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cContenedorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cRelacionaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cRelacionaAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final CrossReference cRelacionaContenedorCrossReference_3_2_0 = (CrossReference)cRelacionaAssignment_3_2.eContents().get(0);
		private final RuleCall cRelacionaContenedorEStringParserRuleCall_3_2_0_1 = (RuleCall)cRelacionaContenedorCrossReference_3_2_0.eContents().get(1);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cRelacionaAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final CrossReference cRelacionaContenedorCrossReference_3_3_1_0 = (CrossReference)cRelacionaAssignment_3_3_1.eContents().get(0);
		private final RuleCall cRelacionaContenedorEStringParserRuleCall_3_3_1_0_1 = (RuleCall)cRelacionaContenedorCrossReference_3_3_1_0.eContents().get(1);
		private final Keyword cRightSquareBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cPoseeKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cPoseeAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cPoseeElementoParserRuleCall_6_0 = (RuleCall)cPoseeAssignment_6.eContents().get(0);
		private final Assignment cPoseeAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cPoseeElementoParserRuleCall_7_0 = (RuleCall)cPoseeAssignment_7.eContents().get(0);
		private final Keyword cSemicolonKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cEsMainKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Keyword cEqualsSignKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Assignment cMainAssignment_12 = (Assignment)cGroup.eContents().get(12);
		private final RuleCall cMainEBooleanParserRuleCall_12_0 = (RuleCall)cMainAssignment_12.eContents().get(0);
		private final Keyword cSemicolonKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Keyword cEsVisualKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cEqualsSignKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cEsVisualAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cEsVisualEBooleanParserRuleCall_16_0 = (RuleCall)cEsVisualAssignment_16.eContents().get(0);
		private final Keyword cSemicolonKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cRightCurlyBracketKeyword_18 = (Keyword)cGroup.eContents().get(18);
		
		//Contenedor returns Contenedor:
		//    'Contenedor'
		//    name=EString
		//    '{'
		//        ('relaciona' '[' relaciona+=[Contenedor|EString] ( "," relaciona+=[Contenedor|EString])* ']' )?
		//        'posee' '{' posee+=Elemento (posee+=Elemento)* ';' '}'
		//        'esMain''='main=EBoolean ';'
		//        'esVisual''='esVisual=EBoolean ';'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Contenedor'
		//name=EString
		//'{'
		//    ('relaciona' '[' relaciona+=[Contenedor|EString] ( "," relaciona+=[Contenedor|EString])* ']' )?
		//    'posee' '{' posee+=Elemento (posee+=Elemento)* ';' '}'
		//    'esMain''='main=EBoolean ';'
		//    'esVisual''='esVisual=EBoolean ';'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Contenedor'
		public Keyword getContenedorKeyword_0() { return cContenedorKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('relaciona' '[' relaciona+=[Contenedor|EString] ( "," relaciona+=[Contenedor|EString])* ']' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'relaciona'
		public Keyword getRelacionaKeyword_3_0() { return cRelacionaKeyword_3_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_1() { return cLeftSquareBracketKeyword_3_1; }
		
		//relaciona+=[Contenedor|EString]
		public Assignment getRelacionaAssignment_3_2() { return cRelacionaAssignment_3_2; }
		
		//[Contenedor|EString]
		public CrossReference getRelacionaContenedorCrossReference_3_2_0() { return cRelacionaContenedorCrossReference_3_2_0; }
		
		//EString
		public RuleCall getRelacionaContenedorEStringParserRuleCall_3_2_0_1() { return cRelacionaContenedorEStringParserRuleCall_3_2_0_1; }
		
		//( "," relaciona+=[Contenedor|EString])*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//relaciona+=[Contenedor|EString]
		public Assignment getRelacionaAssignment_3_3_1() { return cRelacionaAssignment_3_3_1; }
		
		//[Contenedor|EString]
		public CrossReference getRelacionaContenedorCrossReference_3_3_1_0() { return cRelacionaContenedorCrossReference_3_3_1_0; }
		
		//EString
		public RuleCall getRelacionaContenedorEStringParserRuleCall_3_3_1_0_1() { return cRelacionaContenedorEStringParserRuleCall_3_3_1_0_1; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_4() { return cRightSquareBracketKeyword_3_4; }
		
		//'posee'
		public Keyword getPoseeKeyword_4() { return cPoseeKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//posee+=Elemento
		public Assignment getPoseeAssignment_6() { return cPoseeAssignment_6; }
		
		//Elemento
		public RuleCall getPoseeElementoParserRuleCall_6_0() { return cPoseeElementoParserRuleCall_6_0; }
		
		//(posee+=Elemento)*
		public Assignment getPoseeAssignment_7() { return cPoseeAssignment_7; }
		
		//Elemento
		public RuleCall getPoseeElementoParserRuleCall_7_0() { return cPoseeElementoParserRuleCall_7_0; }
		
		//';'
		public Keyword getSemicolonKeyword_8() { return cSemicolonKeyword_8; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
		
		//'esMain'
		public Keyword getEsMainKeyword_10() { return cEsMainKeyword_10; }
		
		//'='
		public Keyword getEqualsSignKeyword_11() { return cEqualsSignKeyword_11; }
		
		//main=EBoolean
		public Assignment getMainAssignment_12() { return cMainAssignment_12; }
		
		//EBoolean
		public RuleCall getMainEBooleanParserRuleCall_12_0() { return cMainEBooleanParserRuleCall_12_0; }
		
		//';'
		public Keyword getSemicolonKeyword_13() { return cSemicolonKeyword_13; }
		
		//'esVisual'
		public Keyword getEsVisualKeyword_14() { return cEsVisualKeyword_14; }
		
		//'='
		public Keyword getEqualsSignKeyword_15() { return cEqualsSignKeyword_15; }
		
		//esVisual=EBoolean
		public Assignment getEsVisualAssignment_16() { return cEsVisualAssignment_16; }
		
		//EBoolean
		public RuleCall getEsVisualEBooleanParserRuleCall_16_0() { return cEsVisualEBooleanParserRuleCall_16_0; }
		
		//';'
		public Keyword getSemicolonKeyword_17() { return cSemicolonKeyword_17; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_18() { return cRightCurlyBracketKeyword_18; }
	}
	public class ElementoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.Elemento");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cElementoKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cLongitudKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cEqualsSignKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLongitudAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLongitudEIntParserRuleCall_5_0 = (RuleCall)cLongitudAssignment_5.eContents().get(0);
		private final Keyword cSemicolonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cTipoDatoKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cEqualsSignKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cTipoDatoAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cTipoDatoTipoDatoEnumRuleCall_7_2_0 = (RuleCall)cTipoDatoAssignment_7_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Keyword cIsPrimaryKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cEqualsSignKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cIsPrimaryAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cIsPrimaryEBooleanParserRuleCall_10_0 = (RuleCall)cIsPrimaryAssignment_10.eContents().get(0);
		private final Keyword cSemicolonKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cEsObligatorioKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cEqualsSignKeyword_13 = (Keyword)cGroup.eContents().get(13);
		private final Assignment cEsObligatorioAssignment_14 = (Assignment)cGroup.eContents().get(14);
		private final RuleCall cEsObligatorioEBooleanParserRuleCall_14_0 = (RuleCall)cEsObligatorioAssignment_14.eContents().get(0);
		private final Keyword cSemicolonKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Keyword cRightCurlyBracketKeyword_16 = (Keyword)cGroup.eContents().get(16);
		
		//Elemento returns Elemento:
		//    'Elemento'
		//    name=EString
		//    '{'
		//        'longitud''='longitud=EInt';'
		//        ('tipoDato''='tipoDato=TipoDato';')?
		//        'isPrimary''='isPrimary=EBoolean ';'
		//        'esObligatorio' '='esObligatorio=EBoolean';'
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Elemento'
		//name=EString
		//'{'
		//    'longitud''='longitud=EInt';'
		//    ('tipoDato''='tipoDato=TipoDato';')?
		//    'isPrimary''='isPrimary=EBoolean ';'
		//    'esObligatorio' '='esObligatorio=EBoolean';'
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Elemento'
		public Keyword getElementoKeyword_0() { return cElementoKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'longitud'
		public Keyword getLongitudKeyword_3() { return cLongitudKeyword_3; }
		
		//'='
		public Keyword getEqualsSignKeyword_4() { return cEqualsSignKeyword_4; }
		
		//longitud=EInt
		public Assignment getLongitudAssignment_5() { return cLongitudAssignment_5; }
		
		//EInt
		public RuleCall getLongitudEIntParserRuleCall_5_0() { return cLongitudEIntParserRuleCall_5_0; }
		
		//';'
		public Keyword getSemicolonKeyword_6() { return cSemicolonKeyword_6; }
		
		//('tipoDato''='tipoDato=TipoDato';')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'tipoDato'
		public Keyword getTipoDatoKeyword_7_0() { return cTipoDatoKeyword_7_0; }
		
		//'='
		public Keyword getEqualsSignKeyword_7_1() { return cEqualsSignKeyword_7_1; }
		
		//tipoDato=TipoDato
		public Assignment getTipoDatoAssignment_7_2() { return cTipoDatoAssignment_7_2; }
		
		//TipoDato
		public RuleCall getTipoDatoTipoDatoEnumRuleCall_7_2_0() { return cTipoDatoTipoDatoEnumRuleCall_7_2_0; }
		
		//';'
		public Keyword getSemicolonKeyword_7_3() { return cSemicolonKeyword_7_3; }
		
		//'isPrimary'
		public Keyword getIsPrimaryKeyword_8() { return cIsPrimaryKeyword_8; }
		
		//'='
		public Keyword getEqualsSignKeyword_9() { return cEqualsSignKeyword_9; }
		
		//isPrimary=EBoolean
		public Assignment getIsPrimaryAssignment_10() { return cIsPrimaryAssignment_10; }
		
		//EBoolean
		public RuleCall getIsPrimaryEBooleanParserRuleCall_10_0() { return cIsPrimaryEBooleanParserRuleCall_10_0; }
		
		//';'
		public Keyword getSemicolonKeyword_11() { return cSemicolonKeyword_11; }
		
		//'esObligatorio'
		public Keyword getEsObligatorioKeyword_12() { return cEsObligatorioKeyword_12; }
		
		//'='
		public Keyword getEqualsSignKeyword_13() { return cEqualsSignKeyword_13; }
		
		//esObligatorio=EBoolean
		public Assignment getEsObligatorioAssignment_14() { return cEsObligatorioAssignment_14; }
		
		//EBoolean
		public RuleCall getEsObligatorioEBooleanParserRuleCall_14_0() { return cEsObligatorioEBooleanParserRuleCall_14_0; }
		
		//';'
		public Keyword getSemicolonKeyword_15() { return cSemicolonKeyword_15; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_16() { return cRightCurlyBracketKeyword_16; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class TipoDatoElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "guiaApe5.GuiaApe5.TipoDato");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStringEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStringStringKeyword_0_0 = (Keyword)cStringEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cIntEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cIntIntKeyword_1_0 = (Keyword)cIntEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBooleanEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBooleanBooleanKeyword_2_0 = (Keyword)cBooleanEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cDoubleEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cDoubleDoubleKeyword_3_0 = (Keyword)cDoubleEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum TipoDato returns TipoDato:
		//                String = 'String' | int = 'int' | boolean = 'boolean' | double = 'double';
		public EnumRule getRule() { return rule; }
		
		//String = 'String' | int = 'int' | boolean = 'boolean' | double = 'double'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//String = 'String'
		public EnumLiteralDeclaration getStringEnumLiteralDeclaration_0() { return cStringEnumLiteralDeclaration_0; }
		
		//'String'
		public Keyword getStringStringKeyword_0_0() { return cStringStringKeyword_0_0; }
		
		//int = 'int'
		public EnumLiteralDeclaration getIntEnumLiteralDeclaration_1() { return cIntEnumLiteralDeclaration_1; }
		
		//'int'
		public Keyword getIntIntKeyword_1_0() { return cIntIntKeyword_1_0; }
		
		//boolean = 'boolean'
		public EnumLiteralDeclaration getBooleanEnumLiteralDeclaration_2() { return cBooleanEnumLiteralDeclaration_2; }
		
		//'boolean'
		public Keyword getBooleanBooleanKeyword_2_0() { return cBooleanBooleanKeyword_2_0; }
		
		//double = 'double'
		public EnumLiteralDeclaration getDoubleEnumLiteralDeclaration_3() { return cDoubleEnumLiteralDeclaration_3; }
		
		//'double'
		public Keyword getDoubleDoubleKeyword_3_0() { return cDoubleDoubleKeyword_3_0; }
	}
	
	private final SistemaElements pSistema;
	private final EStringElements pEString;
	private final ContenedorElements pContenedor;
	private final ElementoElements pElemento;
	private final EBooleanElements pEBoolean;
	private final EIntElements pEInt;
	private final TipoDatoElements eTipoDato;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public GuiaApe5GrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pSistema = new SistemaElements();
		this.pEString = new EStringElements();
		this.pContenedor = new ContenedorElements();
		this.pElemento = new ElementoElements();
		this.pEBoolean = new EBooleanElements();
		this.pEInt = new EIntElements();
		this.eTipoDato = new TipoDatoElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("guiaApe5.GuiaApe5".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Sistema returns Sistema:
	//    'Sistema'
	//    name=EString
	//    '{'
	//        'contiene' '=' '{' contiene+=Contenedor (',' contiene+=Contenedor)* '}'
	//    '}';
	public SistemaElements getSistemaAccess() {
		return pSistema;
	}
	
	public ParserRule getSistemaRule() {
		return getSistemaAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Contenedor returns Contenedor:
	//    'Contenedor'
	//    name=EString
	//    '{'
	//        ('relaciona' '[' relaciona+=[Contenedor|EString] ( "," relaciona+=[Contenedor|EString])* ']' )?
	//        'posee' '{' posee+=Elemento (posee+=Elemento)* ';' '}'
	//        'esMain''='main=EBoolean ';'
	//        'esVisual''='esVisual=EBoolean ';'
	//    '}';
	public ContenedorElements getContenedorAccess() {
		return pContenedor;
	}
	
	public ParserRule getContenedorRule() {
		return getContenedorAccess().getRule();
	}
	
	//Elemento returns Elemento:
	//    'Elemento'
	//    name=EString
	//    '{'
	//        'longitud''='longitud=EInt';'
	//        ('tipoDato''='tipoDato=TipoDato';')?
	//        'isPrimary''='isPrimary=EBoolean ';'
	//        'esObligatorio' '='esObligatorio=EBoolean';'
	//    '}';
	public ElementoElements getElementoAccess() {
		return pElemento;
	}
	
	public ParserRule getElementoRule() {
		return getElementoAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum TipoDato returns TipoDato:
	//                String = 'String' | int = 'int' | boolean = 'boolean' | double = 'double';
	public TipoDatoElements getTipoDatoAccess() {
		return eTipoDato;
	}
	
	public EnumRule getTipoDatoRule() {
		return getTipoDatoAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
