/*
 * generated by Xtext 2.38.0
 */
package guiaApe5;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GuiaApe5StandaloneSetup extends GuiaApe5StandaloneSetupGenerated {

	public static void doSetup() {
		new GuiaApe5StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
