/*
 * generated by Xtext 2.38.0
 */
package guiaApe5;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GuiaApe5RuntimeModule extends AbstractGuiaApe5RuntimeModule {
}
