/*
 * generated by Xtext 2.38.0
 */
package guiaApe5.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractGuiaApe5ScopeProvider extends DelegatingScopeProvider {
}
